---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-carousel-live
  namespace: news
  labels:
    app.kubernetes.io/instance: news-carousel-live
    app: news-carousel-live
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: news-carousel-live
  template:
    metadata:
      labels:
        app: news-carousel-live
    spec:
      containers:
        - name: news-carousel-live
          image: news-carousel-live
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: mqtt-proxy
              containerPort: 30218
              protocol: TCP
          env:
            - name: MQTT_HOST
              value: "192.168.0.100"
            - name: MQTT_PORT
              value: "30217"
            - name: PROXY_PORT
              value: "30218"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
