apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: news
  newName: brucorreia/news-carousel-live
  newTag: 1ace05c5842ca1b32812b663f51859b6548e81f1
- name: news-carousel-live
  newName: brucorreia/news-carousel-live
  newTag: 44d8fcb5e5608e77dd9b49e0b70c2674c71b983f
